### ISSUE TITLE
Refléxion : Fixup, rebase et validation

### ISSUE THREAD

**Issue by EmmanuelPREVOST** [Interencheres/bootstrap#4]
J'ouvre cette issue afin de discuter et valider la méthode de validation des P.R.
Effectivement le `git commit --fixup` est pratique mais ne "permet pas" le ~~le~~ **merge** de la P.R. dans le master sans au préalable avoir fais un `git rebase -i --autosquash`.

Cependant en faisant le **rebase** avant que la P.R. soit valider on risque de faire disparaitre des commentaire fais directement sur des commits, ce qui est assez embetant.

Une solution serait de laisse les **fixup** jusqu'au passage en **status:ready** de la P.R. qui sera alors mergé par le propriétaire de la P.R. après le `git rebase -i --autosquash`.

Bien entendu cela s'applique seulement  sur les P.R. nécessitant un rebase.

A vos clavier !

**Comment by EmmanuelPREVOST** [comment]
@dt-cpm

**Comment by eilgin** [comment]
ca reste en accord avec le _statu quo_. Ca sera plus interessant de mettre ca dans la page "workflow github" de confluence.

**Comment by EmmanuelPREVOST** [comment]
Concernant les fixup on etait pas totalement fixé (jeu de jambes) du moins officiellement

**Comment by EmmanuelPREVOST** [comment]
Vu
